[2023-12-04T09:17:15.419+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-12-01T21:10:00+00:00 [queued]>
[2023-12-04T09:17:15.425+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-12-01T21:10:00+00:00 [queued]>
[2023-12-04T09:17:15.425+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T09:17:15.435+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): updates> on 2023-12-01 21:10:00+00:00
[2023-12-04T09:17:15.439+0000] {standard_task_runner.py:57} INFO - Started process 833 to run task
[2023-12-04T09:17:15.441+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'updates', 'scheduled__2023-12-01T21:10:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp1alpqb84']
[2023-12-04T09:17:15.442+0000] {standard_task_runner.py:85} INFO - Job 36: Subtask updates
[2023-12-04T09:17:15.475+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.updates scheduled__2023-12-01T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T09:17:15.537+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='updates' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T21:10:00+00:00'
[2023-12-04T09:17:15.538+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T09:17:15.539+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip3 install kaggle']
[2023-12-04T09:17:15.548+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T09:17:16.446+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-12-04T09:17:16.614+0000] {subprocess.py:93} INFO - Requirement already satisfied: kaggle in /home/***/.local/lib/python3.8/site-packages (1.5.16)
[2023-12-04T09:17:16.619+0000] {subprocess.py:93} INFO - Requirement already satisfied: bleach in /home/***/.local/lib/python3.8/site-packages (from kaggle) (6.1.0)
[2023-12-04T09:17:16.620+0000] {subprocess.py:93} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.31.0)
[2023-12-04T09:17:16.620+0000] {subprocess.py:93} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2023.7.22)
[2023-12-04T09:17:16.621+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-slugify in /home/***/.local/lib/python3.8/site-packages (from kaggle) (8.0.1)
[2023-12-04T09:17:16.621+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.8.2)
[2023-12-04T09:17:16.621+0000] {subprocess.py:93} INFO - Requirement already satisfied: tqdm in /home/***/.local/lib/python3.8/site-packages (from kaggle) (4.66.1)
[2023-12-04T09:17:16.621+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.26.16)
[2023-12-04T09:17:16.622+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.10 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.16.0)
[2023-12-04T09:17:16.626+0000] {subprocess.py:93} INFO - Requirement already satisfied: webencodings in /home/***/.local/lib/python3.8/site-packages (from bleach->kaggle) (0.5.1)
[2023-12-04T09:17:16.630+0000] {subprocess.py:93} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.8/site-packages (from python-slugify->kaggle) (1.3)
[2023-12-04T09:17:16.635+0000] {subprocess.py:93} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.4)
[2023-12-04T09:17:16.636+0000] {subprocess.py:93} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.2.0)
[2023-12-04T09:17:20.213+0000] {subprocess.py:93} INFO - 
[2023-12-04T09:17:20.214+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.3.1
[2023-12-04T09:17:20.214+0000] {subprocess.py:93} INFO - [notice] To update, run: pip install --upgrade pip
[2023-12-04T09:17:20.351+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-04T09:17:20.368+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=Georgy, task_id=updates, execution_date=20231201T211000, start_date=20231204T091715, end_date=20231204T091720
[2023-12-04T09:17:20.388+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-04T09:17:20.404+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-04T10:24:06.012+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-12-01T21:10:00+00:00 [queued]>
[2023-12-04T10:24:06.017+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-12-01T21:10:00+00:00 [queued]>
[2023-12-04T10:24:06.017+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T10:24:06.027+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): updates> on 2023-12-01 21:10:00+00:00
[2023-12-04T10:24:06.031+0000] {standard_task_runner.py:57} INFO - Started process 1941 to run task
[2023-12-04T10:24:06.033+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'updates', 'scheduled__2023-12-01T21:10:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmplk6hxqyx']
[2023-12-04T10:24:06.034+0000] {standard_task_runner.py:85} INFO - Job 49: Subtask updates
[2023-12-04T10:24:06.065+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.updates scheduled__2023-12-01T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T10:24:06.117+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='updates' AIRFLOW_CTX_EXECUTION_DATE='2023-12-01T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-01T21:10:00+00:00'
[2023-12-04T10:24:06.118+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T10:24:06.118+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip3 install kaggle']
[2023-12-04T10:24:06.126+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T10:24:07.056+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-12-04T10:24:07.220+0000] {subprocess.py:93} INFO - Requirement already satisfied: kaggle in /home/***/.local/lib/python3.8/site-packages (1.5.16)
[2023-12-04T10:24:07.224+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.26.16)
[2023-12-04T10:24:07.225+0000] {subprocess.py:93} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2023.7.22)
[2023-12-04T10:24:07.225+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.10 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.16.0)
[2023-12-04T10:24:07.225+0000] {subprocess.py:93} INFO - Requirement already satisfied: bleach in /home/***/.local/lib/python3.8/site-packages (from kaggle) (6.1.0)
[2023-12-04T10:24:07.226+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.8.2)
[2023-12-04T10:24:07.226+0000] {subprocess.py:93} INFO - Requirement already satisfied: tqdm in /home/***/.local/lib/python3.8/site-packages (from kaggle) (4.66.1)
[2023-12-04T10:24:07.226+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-slugify in /home/***/.local/lib/python3.8/site-packages (from kaggle) (8.0.1)
[2023-12-04T10:24:07.227+0000] {subprocess.py:93} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.31.0)
[2023-12-04T10:24:07.230+0000] {subprocess.py:93} INFO - Requirement already satisfied: webencodings in /home/***/.local/lib/python3.8/site-packages (from bleach->kaggle) (0.5.1)
[2023-12-04T10:24:07.235+0000] {subprocess.py:93} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.8/site-packages (from python-slugify->kaggle) (1.3)
[2023-12-04T10:24:07.240+0000] {subprocess.py:93} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.4)
[2023-12-04T10:24:07.241+0000] {subprocess.py:93} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.2.0)
[2023-12-04T10:24:10.960+0000] {subprocess.py:93} INFO - 
[2023-12-04T10:24:10.960+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.3.1
[2023-12-04T10:24:10.960+0000] {subprocess.py:93} INFO - [notice] To update, run: pip install --upgrade pip
[2023-12-04T10:24:11.137+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-04T10:24:11.155+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=Georgy, task_id=updates, execution_date=20231201T211000, start_date=20231204T102406, end_date=20231204T102411
[2023-12-04T10:24:11.171+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-04T10:24:11.190+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
