[2023-12-04T09:17:23.414+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-12-02T21:10:00+00:00 [queued]>
[2023-12-04T09:17:23.420+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-12-02T21:10:00+00:00 [queued]>
[2023-12-04T09:17:23.421+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T09:17:23.430+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): updates> on 2023-12-02 21:10:00+00:00
[2023-12-04T09:17:23.435+0000] {standard_task_runner.py:57} INFO - Started process 849 to run task
[2023-12-04T09:17:23.437+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'updates', 'scheduled__2023-12-02T21:10:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpl8w5j5sv']
[2023-12-04T09:17:23.438+0000] {standard_task_runner.py:85} INFO - Job 37: Subtask updates
[2023-12-04T09:17:23.471+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.updates scheduled__2023-12-02T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T09:17:23.526+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='updates' AIRFLOW_CTX_EXECUTION_DATE='2023-12-02T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-02T21:10:00+00:00'
[2023-12-04T09:17:23.528+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T09:17:23.529+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip3 install kaggle']
[2023-12-04T09:17:23.538+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T09:17:24.411+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-12-04T09:17:24.578+0000] {subprocess.py:93} INFO - Requirement already satisfied: kaggle in /home/***/.local/lib/python3.8/site-packages (1.5.16)
[2023-12-04T09:17:24.581+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.26.16)
[2023-12-04T09:17:24.582+0000] {subprocess.py:93} INFO - Requirement already satisfied: bleach in /home/***/.local/lib/python3.8/site-packages (from kaggle) (6.1.0)
[2023-12-04T09:17:24.582+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.10 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.16.0)
[2023-12-04T09:17:24.583+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-slugify in /home/***/.local/lib/python3.8/site-packages (from kaggle) (8.0.1)
[2023-12-04T09:17:24.583+0000] {subprocess.py:93} INFO - Requirement already satisfied: tqdm in /home/***/.local/lib/python3.8/site-packages (from kaggle) (4.66.1)
[2023-12-04T09:17:24.583+0000] {subprocess.py:93} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.31.0)
[2023-12-04T09:17:24.584+0000] {subprocess.py:93} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2023.7.22)
[2023-12-04T09:17:24.584+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.8.2)
[2023-12-04T09:17:24.588+0000] {subprocess.py:93} INFO - Requirement already satisfied: webencodings in /home/***/.local/lib/python3.8/site-packages (from bleach->kaggle) (0.5.1)
[2023-12-04T09:17:24.592+0000] {subprocess.py:93} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.8/site-packages (from python-slugify->kaggle) (1.3)
[2023-12-04T09:17:24.597+0000] {subprocess.py:93} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.4)
[2023-12-04T09:17:24.598+0000] {subprocess.py:93} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.2.0)
[2023-12-04T09:17:28.264+0000] {subprocess.py:93} INFO - 
[2023-12-04T09:17:28.264+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.3.1
[2023-12-04T09:17:28.265+0000] {subprocess.py:93} INFO - [notice] To update, run: pip install --upgrade pip
[2023-12-04T09:17:28.404+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-04T09:17:28.430+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=Georgy, task_id=updates, execution_date=20231202T211000, start_date=20231204T091723, end_date=20231204T091728
[2023-12-04T09:17:28.465+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-04T09:17:28.480+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-04T10:24:19.240+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-12-02T21:10:00+00:00 [queued]>
[2023-12-04T10:24:19.246+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Georgy.updates scheduled__2023-12-02T21:10:00+00:00 [queued]>
[2023-12-04T10:24:19.246+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 4
[2023-12-04T10:24:19.257+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): updates> on 2023-12-02 21:10:00+00:00
[2023-12-04T10:24:19.262+0000] {standard_task_runner.py:57} INFO - Started process 1959 to run task
[2023-12-04T10:24:19.264+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Georgy', 'updates', 'scheduled__2023-12-02T21:10:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpxsgdoqjh']
[2023-12-04T10:24:19.265+0000] {standard_task_runner.py:85} INFO - Job 52: Subtask updates
[2023-12-04T10:24:19.301+0000] {task_command.py:415} INFO - Running <TaskInstance: Georgy.updates scheduled__2023-12-02T21:10:00+00:00 [running]> on host ed47267dc344
[2023-12-04T10:24:19.357+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Gio' AIRFLOW_CTX_DAG_ID='Georgy' AIRFLOW_CTX_TASK_ID='updates' AIRFLOW_CTX_EXECUTION_DATE='2023-12-02T21:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-02T21:10:00+00:00'
[2023-12-04T10:24:19.359+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-04T10:24:19.359+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'pip3 install kaggle']
[2023-12-04T10:24:19.367+0000] {subprocess.py:86} INFO - Output:
[2023-12-04T10:24:20.268+0000] {subprocess.py:93} INFO - Defaulting to user installation because normal site-packages is not writeable
[2023-12-04T10:24:20.444+0000] {subprocess.py:93} INFO - Requirement already satisfied: kaggle in /home/***/.local/lib/python3.8/site-packages (1.5.16)
[2023-12-04T10:24:20.448+0000] {subprocess.py:93} INFO - Requirement already satisfied: tqdm in /home/***/.local/lib/python3.8/site-packages (from kaggle) (4.66.1)
[2023-12-04T10:24:20.449+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-dateutil in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.8.2)
[2023-12-04T10:24:20.449+0000] {subprocess.py:93} INFO - Requirement already satisfied: urllib3 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.26.16)
[2023-12-04T10:24:20.449+0000] {subprocess.py:93} INFO - Requirement already satisfied: certifi in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2023.7.22)
[2023-12-04T10:24:20.450+0000] {subprocess.py:93} INFO - Requirement already satisfied: requests in /home/***/.local/lib/python3.8/site-packages (from kaggle) (2.31.0)
[2023-12-04T10:24:20.450+0000] {subprocess.py:93} INFO - Requirement already satisfied: bleach in /home/***/.local/lib/python3.8/site-packages (from kaggle) (6.1.0)
[2023-12-04T10:24:20.451+0000] {subprocess.py:93} INFO - Requirement already satisfied: six>=1.10 in /home/***/.local/lib/python3.8/site-packages (from kaggle) (1.16.0)
[2023-12-04T10:24:20.451+0000] {subprocess.py:93} INFO - Requirement already satisfied: python-slugify in /home/***/.local/lib/python3.8/site-packages (from kaggle) (8.0.1)
[2023-12-04T10:24:20.455+0000] {subprocess.py:93} INFO - Requirement already satisfied: webencodings in /home/***/.local/lib/python3.8/site-packages (from bleach->kaggle) (0.5.1)
[2023-12-04T10:24:20.459+0000] {subprocess.py:93} INFO - Requirement already satisfied: text-unidecode>=1.3 in /home/***/.local/lib/python3.8/site-packages (from python-slugify->kaggle) (1.3)
[2023-12-04T10:24:20.465+0000] {subprocess.py:93} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.2.0)
[2023-12-04T10:24:20.465+0000] {subprocess.py:93} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests->kaggle) (3.4)
[2023-12-04T10:24:24.337+0000] {subprocess.py:93} INFO - 
[2023-12-04T10:24:24.338+0000] {subprocess.py:93} INFO - [notice] A new release of pip is available: 23.0.1 -> 23.3.1
[2023-12-04T10:24:24.339+0000] {subprocess.py:93} INFO - [notice] To update, run: pip install --upgrade pip
[2023-12-04T10:24:24.478+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-12-04T10:24:24.497+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=Georgy, task_id=updates, execution_date=20231202T211000, start_date=20231204T102419, end_date=20231204T102424
[2023-12-04T10:24:24.517+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-04T10:24:24.536+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
